version: '3'
services:
  app1:
    build: .
    environment:
      - APP_NAME=App1
    ports:
      - "3005:3005"

  app2:
    build: .
    environment:
      - APP_NAME=App2
    ports:
      - "3006:3005"

  app3:
    build: .
    environment:
      - APP_NAME=App3
    ports:
      - "3007:3005"
